### ISSUE TITLE
滑块距离 None

### ISSUE THREAD

**Issue by riruigit** [chenwei-zhao/captcha-recognizer#10]
![方案2图片](https://github.com/user-attachments/assets/7777ea24-78a1-4c5c-a29d-c2d1fdf34872)
你好，可以试试这个图片吗？

**Comment by chenwei-zhao** [comment]
针对本例，可先使用identify_gap方法识别出滑块缺口，减去偏移量即为原图滑动距离，且本例中前端对图片进行了2:1的缩放，滑动距离应按比例折算

**Comment by riruigit** [comment]
好，我试试。感谢付出。

**Comment by riruigit** [comment]
我昨天尝试了一下，我好像没有发现网页有缩放，你是怎么判断的？感谢

**Comment by chenwei-zhao** [comment]
没有缩放， 我误判了
你给我的测试图片是720*400尺寸，源网站我看是360*200尺寸的，我以为是缩放过的
