### ISSUE TITLE
关于案例9问题

### ISSUE THREAD

**Issue by riruigit** [chenwei-zhao/captcha-recognizer#11]
第一条黑线位置为滑块初始位置，距离图片边框有大概有8个像素的偏移量（offset为8）。
识别只是返回第二个缺口的位置吗？
那这个 偏移量8 如何获取的？我看了那三个方法好像都不合适。
感谢开源

**Comment by chenwei-zhao** [comment]
案例9中，返回的是滑块缺口的左上和右下坐标（坐标原点为图片左上角）
某一种验证码偏移量通常是固定值，通过截图工具测量距离即可， 如下，红框宽度即为偏移量
![image](https://github.com/user-attachments/assets/e505b8f9-b370-4853-8075-14b649e8c9f7)

**Comment by riruigit** [comment]
那可以返回两个滑块的坐标点嘛？
