### ISSUE TITLE
缺口坐标：[] 可信度：0

### ISSUE THREAD

**Issue by YZQ7777** [chenwei-zhao/captcha-recognizer#3]
首先十分感谢作者大大的开源！当我使用这个库的时候，我发现我传入的两张图片都是返回如标题所述的内容：缺口坐标：[] 可信度：0。
即识别失败了，我的图片放在了评论区
![background](https://github.com/user-attachments/assets/6f76316b-5c12-4eee-b28d-40094fbbb176)
![test](https://github.com/user-attachments/assets/6c2c5604-77bf-4200-a3ef-f502958f942d)

**Comment by chenwei-zhao** [comment]
大佬，刚在163看到你的邮件；
能否提供下这种验证码的厂商信息（如腾讯、极验）或者包含此种验证码的页面链接呢？
方便我这边后续兼容这种验证码；
立个Flag, 一周搞定，敬请期待

Yin ***@***.***> 于2024年9月10日周二 14:13写道：

**Comment by chenwei-zhao** [comment]
# 感谢支持 
首先感谢 @YZQ7777 的支持；
# 新版发布
已经发布了支持此类验证码的新版本
`pip install captcha-recognizer==0.2.1`
# 新版识别效果示例如下
![img_1](https://github.com/user-attachments/assets/bdabfea2-46aa-498d-933a-4b4fe0aed1af)
![img_2](https://github.com/user-attachments/assets/c275245d-0b79-486e-9d06-883df993c4f1)
