### ISSUE TITLE
如果有两个缺口怎么办

### ISSUE THREAD

**Issue by EvelynCarter** [chenwei-zhao/captcha-recognizer#5]
如果有两个缺口怎么办
![2](https://github.com/user-attachments/assets/32ba8c1c-fcf2-4952-a0af-db4c6914a424)
这种的无法准确识别

**Comment by chenwei-zhao** [comment]
早上好:
感谢您的关注！
本库可以准确识别部分双缺口验证码，如果无法识别此种验证码，方便提供下此种验证码的页面链接吗？
以便我快速兼容此种验证码。
可以的话，请邮件私我相关链接，以免造成侵权等不必要的麻烦。
163: chenwei_nature@163.com
google:  chenwei.zhaozhao@gmail.com
期待您的回复，感谢！！！

**Comment by chenwei-zhao** [comment]
新版本已兼容，请安装0.3.0以及之后版本
目前分类两种识别（背景图片识别、截图识别）
针对你的案例，请使用截图识别，使用示例如下：

`
# 验证码截图识别
# source传入图片路径或图片对象
# verbose=False表示关闭冗余输出
# show_result 为True展示识别效果图 (生产环境请设置show_result=False)
recognizer = Recognizer()
box, confidence = recognizer.identify_screenshot(source='<image object>', verbose=False, show_result=True)

print(f'缺口坐标: {box}')
print(f'可信度: {confidence}')
"""
打印结果如下:
缺口坐标: [332.2833251953125, 55.69723129272461, 422.9914245605469, 162.34860229492188]
可信度: 0.9590587019920349

坐标原点：图片左上角
缺口方框坐标为缺口方框左上角和右下角距离坐标原点的距离

"""
`
