### ISSUE TITLE
怎样可以对接到autojs上面去

### ISSUE THREAD

**Issue by EvelynCarter** [chenwei-zhao/captcha-recognizer#6]
这套程序，有什么办法适配到autojs上面去

**Comment by chenwei-zhao** [comment]
关于autojs(或其他的编程语言)与python程序的交互，以下是一些建议

1. Http API
让你的Python脚本作为Web服务运行（例如，使用Flask，Django），并通过HTTP请求与Auto.js应用交互
2. 使用云服务
将 Python 程序部署到云服务（如 AWS Lambda, Google Cloud Functions）上，并通过 HTTP API 与之交互
3. 使用 Android 提供的接口或第三方库
某些 Android 库或接口可能允许你以某种方式调用或集成 Python 代码，但这通常不是标准的做法
4. shell
执行shell命令，运行python程序

**Comment by chenwei-zhao** [comment]
@EvelynCarter HTTP API请移步→ [captcha-api](https://github.com/chenwei-zhao/captcha-api)
