### ISSUE TITLE
滑块双缺口识别问题

### ISSUE THREAD

**Issue by lpy30m** [chenwei-zhao/captcha-recognizer#7]
你好，我在识别XXX滑块 的时候，遇到了双缺口导致识别不准确的问题

示例图片如下:
![image](https://github.com/user-attachments/assets/d7966579-35dc-4b52-bfa9-3aae46a6b0f5)

**Comment by chenwei-zhao** [comment]
感谢关注！
案例已收到，会尽快兼容。
敬请期待新版本

**Comment by chenwei-zhao** [comment]
已增强模型的泛化能力，请安装最新版本再次识别
`pip install captcha-recognizer==0.4.0`
