### ISSUE TITLE
缺口坐标：[] 可信度：0

### ISSUE THREAD

**Issue by Martin-tuodou** [chenwei-zhao/captcha-recognizer#8]
首先十分感谢作者大大的开源！当我使用这个库的时候，我发现我传入的图片都是返回如标题所述的内容：缺口坐标：[] 可信度：0。
即识别失败了，我的图片放在了评论区
![img](https://github.com/user-attachments/assets/15f053c6-c5c4-4435-ab1a-b9dfa4e02726)
我的调用代码
![image](https://github.com/user-attachments/assets/744797cd-2ecd-40c9-910a-b7fa17b27b01)

**Comment by chenwei-zhao** [comment]
感谢关注！
从输出结果来看，目前模型不能识别此种类型的验证码；
能否提供进一步的信息（如网页链接，app名称等，或者任何能让我接触到原图片的渠道），以便于我兼容这种验证码；

**Comment by Martin-tuodou** [comment]
你好
这个网站https://member.ic.net.cn/ 
账号gysy5 密码gysy8888
登录后点击最上面账户名进入后台
热卖库存》逐条发布》随意填写一行数据》保存

tips:
尽量不要保存成功
账号密码不要泄露


 
发件人： Zhao Chenwei
发送时间： 2024-11-11 17:34
收件人： chenwei-zhao/captcha-recognizer
抄送： Martin; Author
主题： Re: [chenwei-zhao/captcha-recognizer] 缺口坐标：[] 可信度：0 (Issue #8)
感谢关注！
从输出结果来看，目前模型不能识别此种类型的验证码；
能否提供进一步的信息（如网页链接，app名称等，或者任何能让我接触到原图片的渠道），以便于我兼容这种验证码；

**Comment by chenwei-zhao** [comment]
好的，收到

**Comment by chenwei-zhao** [comment]
新版已兼容
`pip install captcha-recognizer --upgrade`

![image](https://github.com/user-attachments/assets/4732de8b-2ab3-401d-a3b7-be7c6e40e082)

**Comment by Martin-tuodou** [comment]
我试试，谢谢作者大大
