### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by APLaS-Plus** [chenwei-zhao/captcha-recognizer#9]
请问所有的数据集都是大大自己收集并打标的吗？我最近也在做这个，不过网上貌似并没有多少优质的数据集来源🫠

**Comment by chenwei-zhao** [comment]
是的，我自己收集的，一张一张打的标签，从训练效果来看，单种验证码只需要很少的图片

**Comment by qing-shang** [comment]
> 是的，我自己收集的，一张一张打的标签，从训练效果来看，单种验证码只需要很少的图片

能否提供下数据集

**Comment by chenwei-zhao** [comment]
> > 是的，我自己收集的，一张一张打的标签，从训练效果来看，单种验证码只需要很少的图片
> 
> 能否提供下数据集

对于数据集，标注数据花费了很多时间精力，开源数据集需要做一些心理建设

**Comment by qing-shang** [comment]
> 
> 
> 
> > > 是的，我自己收集的，一张一张打的标签，从训练效果来看，单种验证码只需要很少的图片
> > 
> > 能否提供下数据集
> 
> 对于数据集，标注数据花费了很多时间精力，开源数据集需要做一些心理建设

可以私发下吗，我想试试用于回归的鲁棒性，可以看下我训练的，基于cnn![image](https://github.com/user-attachments/assets/d3282671-d263-4857-a7ed-09f4de2ab080)
